### ISSUE TITLE
Sentry-slack raises exception when testing with tags

### ISSUE THREAD

**Issue by cyc** [getsentry/sentry-slack#36]
Sentry version: 7.7.4
Sentry-slack version: 0.5.0

Can consistently reproduce the error by clicking the "Include tags" checkbox and listing a few comma-delimited tags in the "Included tag keys" field, then clicking "Test Configuration". The resulting stack trace is:

```
[ERROR] Plugin(slack) raised an error during test
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/web/helpers.py", line 170, in plugin_config
    test_results = plugin.test_configuration(project)
  File "/usr/local/lib/python2.7/dist-packages/sentry/plugins/bases/notify.py", line 115, in test_configuration
    return self.notify(notification)
  File "/usr/local/lib/python2.7/dist-packages/sentry/../sentry_slack/plugin.py", line 196, in notify
    std_key = TagKey.get_standardized_key(key)
AttributeError: type object 'TagKey' has no attribute 'get_standardized_key'
```

I believe this is not just limited to running "Test Configuration", since it also seems to block actual live records from being sent to slack.

**Comment by mattrobenolt** [comment]
@cyc This version is not compatible with sentry 7.7. It would need 8.1. We're back at tracking this in our setup.py. :(

**Comment by cyc** [comment]
I see. Is there a known-good version of `sentry-slack` that works with `slack==7.7.4`?

**Comment by jmreicha** [comment]
@cyc I just got version `0.4.0` of sentry-slack working.
